# Generated by Django 4.2 on 2023-08-16 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['date'], 'verbose_name': 'Медиа заявок', 'verbose_name_plural': 'Медиа заявок'},
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(default='user', max_length=50, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='media',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='telebot.application', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='media',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
