# Generated by Django 4.2 on 2023-08-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0003_message_file_message_image_message_message_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('open', 'Открыта'), ('in_work', 'В работе'), ('done', 'Выполнено'), ('closed', 'Закрыто')], default='open', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название компании клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fcs',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ФИО клиента'),
        ),
    ]
