# Generated by Django 4.2 on 2023-08-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0005_alter_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время закрытия'),
        ),
        migrations.AddField(
            model_name='application',
            name='grade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка от пользователя'),
        ),
    ]
