# Generated by Django 4.2 on 2023-08-30 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0006_application_completed_time_application_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='company',
        ),
    ]
