# Generated by Django 4.2 on 2023-08-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0007_remove_application_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='export',
            field=models.BooleanField(default=False, verbose_name='Разрешить/Запретить экспорт'),
        ),
    ]
