# Generated by Django 4.2 on 2023-08-30 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0008_client_export'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
    ]
