# Generated by Django 4.2 on 2023-08-30 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0009_delete_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('username', models.CharField(blank=True, help_text='Username клиента', max_length=50, null=True, verbose_name='Username')),
                ('telegram_id', models.BigIntegerField(help_text='Telegram ID пользователя', verbose_name='Telegram ID')),
                ('name', models.CharField(help_text='Имя в Telegram', max_length=255, verbose_name='Имя в Telegram')),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Операторы',
                'verbose_name_plural': 'Операторы',
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='application',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='telebot.operators', verbose_name='Оператор'),
        ),
    ]
