# Generated by Django 4.2 on 2023-09-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0010_operators_application_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_setting', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=4096)),
            ],
        ),
    ]
